version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      # DB_TYPE: postgresdb
      # DB_POSTGRESDB_HOST: postgres
      # DB_POSTGRESDB_PORT: 5432
      # DB_POSTGRESDB_USER: ${POSTGRES_USER}
      # DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      # DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      # N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      # N8N_USER_MANAGEMENT_JWT_SECRET: ${N8N_USER_MANAGEMENT_JWT_SECRET}
      # N8N_EDITOR_BASE_URL: https://n8ntunnel.federicomosqueira.site
      # WEBHOOK_URL: https://n8ntunnel.federicomosqueira.site/
      # N8N_PERSONALIZATION_ENABLED: false
      # N8N_DIAGNOSTICS_ENABLED: false
      # N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      # N8N_TRUSTED_PROXIES: 0.0.0.0/0
      
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_USER_MANAGEMENT_JWT_SECRET: ${N8N_USER_MANAGEMENT_JWT_SECRET}

      N8N_BLOCK_ENV_ACCESS_IN_NODE: false

      N8N_PROTOCOL: https
      N8N_HOST: n8ntunnel.federicomosqueira.site
      N8N_PORT: 5678
      WEBHOOK_URL: https://n8ntunnel.federicomosqueira.site/
      N8N_TRUSTED_PROXIES: 0.0.0.0/0
      N8N_TRUST_PROXY: true
      N8N_SECURE_COOKIE: true
      N8N_SESSION_COOKIE_DOMAIN: n8ntunnel.federicomosqueira.site


      N8N_EDITOR_BASE_URL: https://n8ntunnel.federicomosqueira.site
      N8N_PERSONALIZATION_ENABLED: false
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      NODE_ENV: production

    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    networks:
      - demo

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - demo

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - demo

volumes:
  postgres_storage:
  n8n_storage:
  qdrant_storage:
  ollama_storage:

networks:
  demo:
